name: gramps
version: 'devel'
version-script: python3 -c "from gramps.version import VERSION ; print(VERSION + '-snap1')"
summary: Research, organize and share your family tree with Gramps.
description: |
  Gramps is a free software project and community. We strive to produce
  a genealogy program that is both intuitive for hobbyists and feature-complete
  for professional genealogists. It is a community project, created,
  developed and governed by genealogists.

grade: stable
confinement: strict
base: core18

parts:
  gramps:
    plugin: python
    source: .
    stage-packages:
      - librsvg2-2
      - python3-gi
      - python3-gi-cairo
      - python3-bsddb3
      - xdg-utils
      - graphviz
      - fonts-freefont-ttf
      - gir1.2-gtk-3.0
      - gir1.2-goocanvas-2.0
      - gir1.2-gtkspell3-3.0
      - gir1.2-osmgpsmap-1.0
      - gir1.2-gexiv2-0.10
      - python3-pil
      - python3-icu
      - locales-all
      - libgtk-3-bin
    override-build: |
      sed -i.bak -e 's|Icon=gramps$|Icon=${SNAP}/share/gramps/images/gramps.svg|g' data/gramps.desktop.in
      snapcraftctl build

slots:
  gramps:
    interface: dbus
    bus: session
    name: org.gramps-project.Gramps

apps:
  gramps:
    environment:
      GRAMPSHOME: ${SNAP_USER_COMMON}/
      GRAMPS_RESOURCES: ${SNAP}/share/
    command: bin/gramps
    desktop: share/applications/gramps.desktop
    extensions: [ gnome-3-28 ]
    plugs:
      - cups-control
      - gsettings
      - home
      - network
      - unity7
